#!/bin/sh
SASS="sass --no-source-map ext/main.scss:ext/main.css"
ZIP="zip -D -r -9"

case $1 in

    build )
        "$0" clean
        pkg_name=$(cat ext/manifest.json | jq --raw-output '"\(.applications.gecko.id) \(.version)"')
        $ZIP "$pkg_name.src.zip" . -x '.git/*' '.gitignore'
        $SASS --style=compressed
        (cd ext ; $ZIP "../$pkg_name.zip" . -x '*.scss' '*/scss/*')
        ;;

    watch )
        PIDS=
        trap 'kill $PIDS;echo' INT
        $SASS --watch &
        PIDS="$PIDS $!"
        wait
        ;;

    clean )
        rm --force *.zip "ext/main.css"
        ;;

    * )
        echo "$0 { build | watch }"
        ;;

esac
